### ISSUE TITLE
有关只有实体，没有客体的训练

### ISSUE THREAD

**Issue by leizhu1989** [Xie-Minghui/EntityRelationExtraction#10]
大佬，您好，感谢您的开源获益匪浅
有个问题想请教下：
就是假如我只有实体，没有客体，客体是答案做成了知识图谱那样的，我只想知道问问题的人意图去检索答案，这样的话需要怎么训练呢；比如语料“播放视频很卡是什么原因”，‘’视频没法播放啥原因‘’这样的呢，求大佬指点

**Comment by leizhu1989** [comment]
您代码里面是实体和客体组合在一起做提取的吧，同时提取实体和客体的吧

**Comment by Xie-Minghui** [comment]
> 大佬，您好，感谢您的开源获益匪浅 有个问题想请教下： 就是假如我只有实体，没有客体，客体是答案做成了知识图谱那样的，我只想知道问问题的人意图去检索答案，这样的话需要怎么训练呢；比如语料“播放视频很卡是什么原因”，‘’视频没法播放啥原因‘’这样的呢，求大佬指点

我的好像只支持主客体的训练，因为我的训练数据就是类似模式的。你这个需要构造新的训练语料

**Comment by Xie-Minghui** [comment]
> 您代码里面是实体和客体组合在一起做提取的吧，同时提取实体和客体的吧

是的，同时提取的
