### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 2azhui** [Xie-Minghui/EntityRelationExtraction#9]
你好 为什么dataloader的numwork参数调一下 就会报错ValueError: mask of the first timestep must all be on

**Comment by Xie-Minghui** [comment]
不知道，num_worker >1之后，就会数据并行，然后报错。因为数据本身不大，所以num_worker设置为1就够了

**Comment by Xie-Minghui** [comment]
> 你好 为什么dataloader的numwork参数调一下 就会报错ValueError: mask of the first timestep must all be on

不知道，num_worker >1之后，就会数据并行，然后报错。因为数据本身不大，所以num_worker设置为1就够了

**Comment by 2azhui** [comment]
网上说是windows的bug

**Comment by Xie-Minghui** [comment]
> 网上说是windows的bug

哦哦

**Comment by Xie-Minghui** [comment]
> 网上说是windows的bug

你知道怎么改了，麻烦告诉我，谢谢

**Comment by 2azhui** [comment]
好的
